name: "Pull Request Labeler"
on:
  pull_request:
    branches:
      - main

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Apply Labels
        uses: actions/labeler@v4
        with:
          configuration-path: ".github/actions-config.yml"
          sync-labels: true
      - name: Assign PR
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: ".github/actions-config.yml"
